name: Lint and Start

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-and-start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install flake8

      - name: Lint with flake8
        continue-on-error: true
        run: flake8 src

      - name: Run application
        env:
          QT_QPA_PLATFORM: offscreen
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libegl1 libgl1 libxcb-cursor0 libxkbcommon-x11-0
          xvfb-run -a timeout 5 python src/main.py
